### ISSUE TITLE
JSON-LD media type

### ISSUE THREAD

**Issue by akuckartz** [3-Round-Stones/callimachus#122]
I have seen that #111 was resolved but what about `application/ld+json` ?

**Comment by DruidSmith** [comment]
Hi James/David - was curious what the plans/roadmap/timeline were for JSON-LD functionality are as described above - and what do you mean in terms of support a.) being able to render out results serialized as JSON-LD? b.) being able to ingest data serialized as JSON-LD? c) SPARQL interactions via JSON-LD (sounds like 1.5.0)?

**Comment by jamesrdf** [comment]
Callimachus 1.4 supports the LDP API and includes support for the JSON-LD format (both reading and writing). Callimachus 1.5.0-beta includes a fix for #192, which includes support for JSON-LD as a SPARQL graph response.

See http://www.w3.org/TR/ldp/#h-ldprs-http_get for more information about LDP and JSON-LD

**Comment by DruidSmith** [comment]
Thanks!  Sounds great!
