### ISSUE TITLE
Update SPARQL Results View

### ISSUE THREAD

**Issue by prototypo** [3-Round-Stones/callimachus#182]
The current SPARQL Results view has some problems:

1. All URIs are currently hyperlinked, but we have moved away from directly resolving most URIs as URLs. Instead, we are encouraging the storage and retrieval of URIs from RDF datasources, so most of them will not be URLs.

2. The chevrons are a bit small and, especially if they will be the only hyperlinks, they should be made larger.

3. Predicates are not always abbreviated, probably because they are not added to the SPARQL Profile if they are not loaded into the default RDF datastore. They should probably be tracked regardless of which datastore they are added to.

4. Selecting some chevrons (DESCRIBE queries?) can result in huge result sets and kill the server for want of heap space. Is there some way to limit the size of the results (e.g. by shifting to an equivalent SELECT with LIMIT?

![sparql results update](https://cloud.githubusercontent.com/assets/824236/4854877/8307d644-609b-11e4-9397-38ee29f4e582.png)

**Comment by jamesrdf** [comment]
With Callimachus 1.5.0 and virtual resources, data source URI might actually be URLs and in Callimachus 2.0.0 URIs that start with the data source URL are expected to resolve.
