### ISSUE TITLE
Potential dangers of reverse lookup in "describe" view

### ISSUE THREAD

**Issue by edwardsph** [3-Round-Stones/callimachus#183]
Whilst viewing https://usepa.3roundstones.net/usepa/data/rcra?query=describe+%3Chttp://usepa.3roundstones.net/rcra/handlers/OHD000816801%3E I made the mistake of clicking the chevrons against the object <http://usepa.3roundstones.net/rcra/land-type/P> (the landType predicate appears after the list of hasActivity predicates). I got no response and the server needed a restart after this due to running out of memory. As soon as I clicked it I realised what would happen but it was too late. 
I believe the problem is that the describe page, as well as describing the object specified, includes a reverse lookup of triples referencing the object. In this case there would have been millions so it highlights how easy it is to cause a problem when you don't have a good understanding of the data. I was clicking around the describe page to try and gain this understanding.

Does the describe page use a select query to perform that reverse lookup and is there a limit on it? Is there anything we can do to protect users from mistakes like this?

**Comment by jamesrdf** [comment]
See also https://openrdf.atlassian.net/browse/SES-1904

**Comment by prototypo** [comment]
Resolution by phone: Perform a count of the describe on each URI in the query results when building the page. The hyperlink on the chevrons will resolve to the SPARQL query page populated with the generated query in the event that the count is "too high", and will include an error message saying that the number of results is too large. Small counts will result in the existing behavior.
