### ISSUE TITLE
Cannot create layout outside home folder

### ISSUE THREAD

**Issue by edwardsph** [3-Round-Stones/callimachus#200]
__Goal__: Create a layout with associated files in a "themes" folder
__Problem__: There doesn't appear to be a way to save a new layout in a sub-folder, nor can you search for an existing layout file.
__Test environment__: Callimachus OS 1.4.0, Windows 7, Chrome browser 39.0.2171.95 m

To reproduce this problem from a clean installation:
* Edit home folder
* Click button beside layout
* __PROBLEM 1__: There is no option to change folder before saving
* Copy the layout file content and cancel the popup
* Create a new folder for the theme
* Create an XQuery file in that folder and paste the layout in
* Edit home folder
* Layout drop-down does not show the new file (nor would I expect it to but I don't know how this list is later populated)
* Click button beside layout
* In the search box type name of new layout
* __PROBLEM 2__: You get a spinner but nothing is found. If you click enter you get an error on the main page and the popup disappears: "Oops! java.lang.NullPointerException in /callimachus/1.4/types/pipeline.ttl#PostResult»"

The workaround was to execute the following spaql:
```
DELETE {
<http://localhost/> <http://callimachusproject.org/rdf/2009/framework#layout> <http://localhost/callimachus/default-layout.xq> 
} INSERT {
<http://localhost/> <http://callimachusproject.org/rdf/2009/framework#layout> <http://localhost/themes/my-layout.xq> 
} WHERE {}
```

**Comment by jamesrdf** [comment]
Such a solution should also include documentation as to how to modify the layout. Such as http://callimachusproject.org/docs/1.3/callimachus-for-web-developers.docbook?view#Home_Folder_Edit_Tab

**Comment by jamesrdf** [comment]
See http://callimachusproject.org/docs/1.4/getting-started-with-callimachus.docbook?view#Home_Folder_Edit_Tab
