### ISSUE TITLE
Documentation changes needed as a result of fixed issue 138 (diverted links)

### ISSUE THREAD

**Issue by edwardsph** [3-Round-Stones/callimachus#205]
The release notes for 1.4.0 do not mention that support for diverted links was dropped in this release. The documentation still has examples of using the "view" class - e.g. http://callimachusproject.org/docs/1.4/callimachus-for-web-developers.docbook?view#Class_Instance_View and http://callimachusproject.org/docs/1.4/callimachus-for-web-developers.docbook?view#Class_Membership_View.

It would be useful to add a pattern for creating pages to view such resources.

**Comment by jamesrdf** [comment]
The class="view" has been removed from both pages in the documentation.
