### ISSUE TITLE
Theme widget missing

### ISSUE THREAD

**Issue by edwardsph** [3-Round-Stones/callimachus#210]
On 1.4.1 RC, whilst editing the home folder, the theme widget mentioned in the documentation is missing. However, you can type a filename in and add it in order to create a new theme in your chosen location.

**Comment by jamesrdf** [comment]
Can you be more specific? Looking at http://callimachusproject.org/docs/1.4/getting-started-with-callimachus.docbook?view it only says "Click the widget below Layout", which is the drop-down/input box below the label and is present.

**Comment by edwardsph** [comment]
Sorry - my misunderstanding. Of course the drop-down is a widget but I was looking for something like the icon beside authentication and credentials.

**Comment by jamesrdf** [comment]
What change to the documentation would you suggest?

**Comment by edwardsph** [comment]
It might be worth avoiding the generic term "widget" and saying "drop-down" or "selector" since that is what it appears to be on first sight. The additional features of the widget are only exposed when you continue with the instructions.
