### ISSUE TITLE
Inappropriate Handing of .m4a Audio Files

### ISSUE THREAD

**Issue by prototypo** [3-Round-Stones/callimachus#216]
Callimachus 1.4 series allows the importation of .m4a audio files, but doesn't know how to handle them.

* The files cannot be served raw; Browsers are redirected back to the ?view pragma.
* The files cannot be edited. See the attached screenshot.

These issues should be addressed, or the capability to upload .m4a files should be removed.

![calli1 4 m4a edit](https://cloud.githubusercontent.com/assets/824236/7252506/aff64470-e803-11e4-9e4d-cac766d8582f.png)

**Comment by jamesrdf** [comment]
It would appear that the system is accepting anything, but doesn't know what to do with it. This bug might have been introduced with the LDP work.

**Comment by prototypo** [comment]
So how do we delete unknown file types that have been added? :)

**Comment by jamesrdf** [comment]
curl --digest --user john -X DELETE http://....

**Comment by prototypo** [comment]
Ah, yes. I should have thought of that.
