### ISSUE TITLE
OWL Class Explorer No Longer Assigns Equivalent Classes

### ISSUE THREAD

**Issue by prototypo** [3-Round-Stones/callimachus#217]
The OWL Class Explorer should assign a Callimachus equivalent class when the "assign templates" link is selected to create a new Callimachus class. This appears to have worked through Callimachus 1.3.4, but stopped working sometime in the 1.4.X series.

To replicate this issue:
* Download the Linked Data book [sample code] (http://www.manning.com/dwood/LinkedDataSourceCode.zip)
* Make a Callimachus folder (e.g. "bonobos")
* Upload the Turtle file ch9listings/listing9_1.ttl into the new folder
* Select the Turtle file
* Using the Callimachus main menu, select "Explore OWL classes in this graph"
* Select the "assign templates" link from the Bonobos class
* Note that no equivalent class is assigned

This bug should also be repaired in 1.4.3, if we produce a 1.4.3 release

![screenshot_858](https://cloud.githubusercontent.com/assets/824236/7277495/65868090-e8de-11e4-83fe-13c518052b92.png)
.

**Comment by jamesrdf** [comment]
This only effects owl:Classes that don't have an rdfs:label.

**Comment by prototypo** [comment]
So? That doesn't mean we should close the issue. We have code in the wild that relied on it working without a label.

**Comment by jamesrdf** [comment]
That was just an FYI. The commit makes rdfs:label optional in the master branch.
