### ISSUE TITLE
Unhelpful error when saving a docbook file

### ISSUE THREAD

**Issue by edwardsph** [3-Round-Stones/callimachus#229]
I have been editing a docbook article and used command formatting in a couple of places. Now I come to save the file I get the error:
Oops!

Document is invalid systemId: myarticle.docbook; lineNumber: 234; columnNumber: 19; element "command" not allowed here; expected the element end-tag or element "address", "anchor", "annotation", "bibliography", "bibliolist", "blockquote", "bridgehead", "calloutlist", "caution", "classsynopsis", "cmdsynopsis", "constraintdef", "constructorsynopsis", "destructorsynopsis", "epigraph", "equation", "example", "fieldsynopsis", "figure", "formalpara", "funcsynopsis", "glossary", "glosslist", "important", "index", "indexterm", "informalequation", "informalexample", "informalfigure", "informaltable", "itemizedlist", "literallayout", "mediaobject", "methodsynopsis", "msgset", "note", "ns:include", "orderedlist", "para", "procedure", "productionset", "programlisting", "programlistingco", "qandaset", "refentry", "refsect1", "remark", "revhistory", "screen", "screenco", "screenshot", "section", "segmentedlist", "sidebar", "simpara", "simplelist", "simplesect", "synopsis", "table", "task", "tip", "toc", "variablelist" or "warning" (with xmlns:ns="/2001/XInclude")

I have looked at the payload sent to the server and it is pseudo-HTML so I imagine the line number is related to an intermediate file. I tracked it down by a bit of guess work and trial and error to this:
    &lt;pre>
    &lt;code class="command">sample code&lt;/code>&lt;/pre>

I removed formatting on this line and it saved. I think I started with an inline command format then changed to using the formatted style. It could do with validating on the client or returning errors that connect to what the user sees.

**Comment by jamesrdf** [comment]
Can you provide steps to reproduce or provide the payload sent to the server that produced this error?

**Comment by edwardsph** [comment]
To reproduce: 
* Create a new article
* In the first paragraph set the inline style to "Command"
* Add some text
* Change the paragraph format to "Formatted"
* Save

**Error**
Document is invalid systemId: /Products/Enviroindex/untitled.docbook; lineNumber: 4; columnNumber: 13; element "command" not allowed here; expected element 

**Payload**
&lt;html xmlns="http://www.w3.org/1999/xhtml">
&lt;head>
	&lt;title>Untitled Article&lt;/title>
	&lt;style type="text/css">&lt;![CDATA[@import url("https://wiki.3roundstones.com/callimachus/1.4/assets/ckeditor/plugins/codesnippet/lib/highlight/styles/github.css");
body { background-color: #f5f5f5; }
body.cke_editable.cke_show_blocks > * { background-color: #fff; padding-bottom: 5px;}
	]]>&lt;/style>
&lt;/head>
&lt;body>
&lt;h1>Untitled Article&lt;/h1>

&lt;pre>
&lt;code class="command">command&lt;/code>&lt;/pre>
&lt;/body>
&lt;/html>
