### ISSUE TITLE
Potential problem with installation on Windows when Git is on path

### ISSUE THREAD

**Issue by edwardsph** [3-Round-Stones/callimachus#231]
After installing Git in Windows I couldn't run the Callimachus setup script. It was complaining it couldn't find "#". On investigation I discovered that Git had put it's bin folder on the path ahead of the windows system folders so the script was using it's find which is not compatible. The solution was to prefix calls to find with "\Windows\System32\" to force the correct one. Do you think this is something worth considering for all commands called from the scripts to make them less vulnerable to path problems?

**Comment by jamesrdf** [comment]
I think windows have an environment variable that include the current path to the windows directory (some OEM installs use a different path). Prefixing the find commend with this windows path variable should be a portable solution to this.

**Comment by edwardsph** [comment]
Good idea. I think the nearest we get is the Windows folder:
On my PC I have:
  SystemRoot=C:\WINDOWS
  windir=C:\WINDOWS
We may need to check further but we could use
  %SystemRoot%\System32\find

Pete
