### ISSUE TITLE
Unclear behaviours when setting up users

### ISSUE THREAD

**Issue by edwardsph** [3-Round-Stones/callimachus#235]
Tested: 1.5.0-beta

1. I tried to change a user's email address by logging in as that user, going to their user page and selecting Change password or email. If you want to change the email address only you are required to enter your password too. So I entered the existing password into both locations and saved. The only  change is that you are signed out but left on the existing page. I don't think this is very clear behaviour - if signing out is important that could it go so a different page so the user knows what is going on?

2. Adding a user to a group, I edited the group and tried to add a user by their username. It is not found. You have to search by something in the full name or email address

3. If you search for users to add to a list and click on one, they are added to the members list. If you click on the entry in the list a popup opens. The server is behind an apache reverse proxy and runs on port 9660 but the port is not in the origin. I got this error in the popup: Origin http://gpo-testbed-calli.3roundstones.net:9660 is not configured, perhaps you wanted http://gpo-testbed-calli.3roundstones.net/. What put the port in the address?

4. When adding a new user to a group it is not clear what to put as the new member name - I was adding user names but I think this is the least useful thing to add. I tried adding my full name "Pete Edwards" but after sending the invitation what ends up in the member select list is a munged version of my email pete_edwards4.co.uk. I realise this is just a temporary token - when I save the group I see "Pete Edwards" in the list and once the invited user has registered the token is replaced by the real name, the username only being used for the calli:name. This was all a bit confusing and I wonder if it could be improved - exposing the calli:name through the search might help.

**Comment by jamesrdf** [comment]
Can you provide more details about the Origin error?
