### ISSUE TITLE
Localhost credential authority is sent as 127.0.0.1

### ISSUE THREAD

**Issue by edwardsph** [3-Round-Stones/callimachus#242]
A credential set up with the authority localhost:3306 is failing to connect to the database with the message:
Could not connect: Access denied for user 'xxxxxx'@'127.0.0.1' (using password: YES)
The database does not have a user account for 'xxxxxx'@'127.0.0.1' only for 'xxxxxx'@'localhost'.

The workaround is to add the additional user to the database but why is localhost being replaced with 127.0.0.1 when the database does not appear to treat them as the same thing.

**Comment by jamesrdf** [comment]
Callimachus' SQL Datasource uses the host in the jdbc URL to lookup the username and password from the credentials. This 127.0.0.1 string, I believe, comes from either the driver's interpretation of the jdbc URL or the network socket interface (and the system's name resolution). Either way, there is nothing Callimachus can do about it.

**Comment by prototypo** [comment]
We will work around this by granting database user permissions on 127.0.0.1 as well as localhost.


Regards,
Dave
-- 
David Wood
http://about.me/david_wood 

On December 10, 2015 at 11:28:43, James Leigh (notifications@github.com) wrote:

Callimachus' SQL Datasource uses the host in the jdbc URL to lookup the username and password from the credentials. This 127.0.0.1 string, I believe, comes from either the driver's interpretation of the jdbc URL or the network socket interface (and the system's name resolution). Either way, there is nothing Callimachus can do about it.

**Comment by edwardsph** [comment]
That's fine if we can't do anything about.
Thanks
Pete
