### ISSUE TITLE
Installing in user directory?

### ISSUE THREAD

**Issue by Hibou57** [3-Round-Stones/callimachus#268]
Just wanted to know if there is a way to install Callimachus in a user's directory. I tried running in from unzipped archive, but it did not work, neither it worked using a more or less tweaked install script, it always complains no web origins are configured.

(hope this question is not too much annoying)

**Comment by catch-point** [comment]
Are you trying to install Callimachus, or move the installed directory
(after you already installed it)?

James

**Comment by Hibou57** [comment]
Hello,

I was trying to install, there was no prior installation before this one. This is just to avoid touching the core system.

**Comment by Hibou57** [comment]
If ever that matters, `uname -a` says:

    Linux XXX 3.13.0-129-generic #178-Ubuntu SMP Fri Aug 11 12:49:13 UTC 2017 i686 i686 i686 GNU/Linux

**Comment by catch-point** [comment]
To install Callimachus on linux use the callimachus-install.sh script as root to setup the init scripts. If that is not desired, don't run the install script and just use the callimachus-setup.sh script.
